version: '2'

services:
  hadoop-master:
    image: 'prestodev/hdp3.1-hive:${DOCKER_IMAGES_VERSION}'

  application-runner:
    environment:
      - TEMPTO_PROFILE_CONFIG_FILE=/docker/volumes/conf/tempto/tempto-configuration-for-hdp3.yaml